default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: blog_db_dev
  host: localhost
  username: ivanna
  password: 1q2w3e

test:
  <<: *default
  database: blog_db_test
  host: localhost
  username: ivanna
  password: 1q2w3e

production:
  <<: *default
  database: blog_db_prod
  username: ivanna
  password: 1q2w3e
